//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project6_CreativeKids.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int ID { get; set; }
        public Nullable<int> product_ID { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> user_ID { get; set; }
        public string productName { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User_Info User_Info { get; set; }
    }
}
